// Dependencias integradas: la app funciona también cuando Opera abre index.html con file://.
// PWA/Service Worker requieren localhost o HTTPS, pero el editor no.
let database;
function openDB(){if(database)return Promise.resolve(database);return new Promise((resolve,reject)=>{const r=indexedDB.open('scriptlab-ai',2);r.onupgradeneeded=()=>{const d=r.result;['projects','snapshots','calibrations','settings','analysisCache','modelRegistry'].forEach(n=>{if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:'id'})})};r.onsuccess=()=>{database=r.result;resolve(database)};r.onerror=()=>reject(r.error)})}
async function put(store,value){const d=await openDB();return new Promise((resolve,reject)=>{const r=d.transaction(store,'readwrite').objectStore(store).put(value);r.onsuccess=()=>resolve(value);r.onerror=()=>reject(r.error)})}
async function get(store,id){const d=await openDB();return new Promise((resolve,reject)=>{const r=d.transaction(store,'readonly').objectStore(store).get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function all(store){const d=await openDB();return new Promise((resolve,reject)=>{const r=d.transaction(store,'readonly').objectStore(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function migrateLegacy(){if(localStorage.getItem('scriptlab-idb-migrated'))return;const raw=localStorage.getItem('scriptlab-ai-project-v1');if(raw)try{const rawProject=JSON.parse(raw),meta=rawProject.project||rawProject;await put('projects',{...meta,id:'active',blocks:Array.isArray(rawProject.blocks)?rawProject.blocks:[],updatedAt:Date.now()})}catch(error){console.warn('No se pudo migrar proyecto anterior',error)}localStorage.setItem('scriptlab-idb-migrated','1')}
function download(data,name,type){const u=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
function fileSlug(text){return(text||'scriptlab').toLowerCase().replace(/[^a-z0-9]+/gi,'-')}
function exportJSON(project,analysis,calibration){download(JSON.stringify({app:'ScriptLab AI',exportedAt:new Date().toISOString(),project,analysis,calibration},null,2),fileSlug(project.title)+'.scriptlab.json','application/json')}
function exportMarkdown(project,analysis){let md='# '+project.title+'\n\n**Promesa:** '+(project.promise||'—')+'\n\n**ICN:** '+analysis.score+'/100\n';project.blocks.forEach((b,i)=>md+='\n## '+(i+1)+'. '+b.type+': '+b.label+'\n\n'+(b.content||'_Sin contenido_')+'\n'+(b.notes?'\n> Nota: '+b.notes+'\n':''));download(md,fileSlug(project.title)+'.md','text/markdown')}
function exportHTML(project,analysis){const clean=v=>String(v||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));const blocks=project.blocks.map((b,i)=>'<section><small>'+ (i+1)+'. '+clean(b.type)+'</small><h2>'+clean(b.label)+'</h2><p>'+clean(b.content).replace(/\n/g,'<br>')+'</p></section>').join('');download('<!doctype html><meta charset="utf-8"><title>'+clean(project.title)+'</title><style>body{font:16px system-ui;max-width:780px;margin:40px auto;line-height:1.6}section{border-left:4px solid #7969ff;padding:10px 20px;margin:15px 0;background:#fafafa;break-inside:avoid}small{color:#555}</style><h1>'+clean(project.title)+'</h1><p>'+clean(project.promise)+'</p><p>ICN '+analysis.score+'/100</p>'+blocks,fileSlug(project.title)+'.html','text/html')}
const T={HOOK:['Hook','#ff7d5c'],CONTEXTO:['Contexto','#69a8ff'],EVIDENCIA:['Evidencia','#ae83ff'],SEGMENTO:['Segmento','#b3bdce'],GIRO:['Giro','#f4b857'],VISUAL:['Nota visual','#32d2ac'],CTA:['CTA','#5cdb87']};let p,sel=null,timer,worker,rev=0,aiResult=null,aiTimer,modelDirectory=null,calRecords=[],analysisDirty=true,cachedAnalysis=null,flowDirty=true,tts={index:0,playing:false,paused:false};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],W=t=>(t||'').trim().match(/[\p{L}\p{N}'’-]+/gu)?.length||0,D=t=>Math.round(W(t)/(p?.wpm||150)*60),time=s=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`,esc=s=>String(s||'').replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]));
function normalizeProject(raw={}){
  // Acepta el esquema actual y la estructura legacy { project, blocks }.
  const meta=raw.project||raw;
  const blocks=Array.isArray(raw.blocks)?raw.blocks:[];
  return {id:'active',title:meta.title||'Nuevo guion',promise:meta.promise||'',aiMode:['basic','embeddings'].includes(meta.aiMode)?meta.aiMode:'basic',blocks:blocks.map((b,i)=>({id:b.id||crypto.randomUUID(),type:T[b.type]?b.type:'SEGMENTO',label:b.label||T[T[b.type]?b.type:'SEGMENTO'][0],content:b.content||'',notes:b.notes||''})),updatedAt:meta.updatedAt||Date.now(),wpm:Math.max(115,Math.min(185,Number(meta.wpm)||150))}
}
async function boot(){await openDB();await migrateLegacy();calRecords=await all('calibrations');p=normalizeProject(await get('projects','active'));Object.entries(T).forEach(([k,[n,c]])=>{$('#palette').insertAdjacentHTML('beforeend',`<button draggable="true" data-type="${k}"><i style="background:${c}"></i>${n}</button>`);$('#type').insertAdjacentHTML('beforeend',`<option value="${k}">${n}</option>`)});bind();render();initWorker(false);window.ScriptLabBooted=true;document.documentElement.dataset.scriptlabReady='true'}
const HEURISTICS=[
{name:'Fernández-Huerta',kind:'Validada',formula:'206.84 − 60×sílabas/palabra − 1.02×palabras/frase',source:'Fernández-Huerta (1959), adaptación española de Flesch.'},
{name:'Hook',kind:'Heurística',formula:'Longitud, pregunta y alineación con promesa',source:'Regla transparente configurable.'},
{name:'Ritmo visual',kind:'Heurística',formula:'Notas visuales y giros por duración',source:'Referencia direccional: Cutting et al. (2016).'},
{name:'CTA',kind:'Heurística',formula:'Presencia de cierre o siguiente acción',source:'Regla estructural interna.'}
];
const syllables=w=>{w=(w||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zñü]/g,'');let n=0,last=false;for(const c of w){const v='aeiouü'.includes(c);if(v&&!last)n++;last=v}return Math.max(1,n)};
const fernandezHuerta=text=>{const ws=(text||'').match(/[\p{L}]+/gu)||[],ss=(text||'').split(/[.!?]+/).filter(x=>x.trim()).length||1;if(!ws.length)return 0;return Math.max(0,Math.min(100,206.84-60*(ws.reduce((n,w)=>n+syllables(w),0)/ws.length)-1.02*(ws.length/ss)))};
function renderHeuristics(){const root=$('#heuristics-catalog');if(root)root.innerHTML=HEURISTICS.map(h=>`<article><b>${h.name}</b><small>${h.kind} · ${h.formula}<br>${h.source}</small></article>`).join('')}
function computeAnalysis(){let text=p.blocks.map(b=>b.content).join(' '),hook=p.blocks.find(b=>b.type==='HOOK'),sent=text.split(/[.!?]+/).filter(Boolean),avg=W(text)/Math.max(1,sent.length),visual=p.blocks.filter(b=>b.type==='VISUAL'||b.type==='GIRO').length,r=[];if(!hook)r.push(['bad','Falta un Hook']);if(hook&&W(hook.content)<12)r.push(['bad','Hook demasiado corto']);if(hook&&p.promise&&!overlap(hook.content,p.promise))r.push(['warn','La promesa no aparece en el Hook']);if(avg>25)r.push(['warn','Oraciones extensas']);if(D(text)>180&&visual<2)r.push(['warn','Ritmo visual bajo']);if(!p.blocks.some(b=>b.type==='CTA'))r.push(['warn','Sin CTA']);p.blocks.forEach(b=>{if(!b.content&&b.type!=='VISUAL')r.push(['bad',`${T[b.type][0]} vacío`,b.id]);if(D(b.content)>65&&['SEGMENTO','CONTEXTO'].includes(b.type))r.push(['warn','Bloque de voz largo',b.id])});let hs=!hook?10:Math.max(0,Math.min(100,40+(W(hook.content)>24&&W(hook.content)<86?28:0)+(overlap(hook.content,p.promise)?20:-8))),fh=fernandezHuerta(text),cl=Math.max(0,Math.min(100,fh*.82-Math.max(0,avg-18)*2+18)),pa=Math.min(100,40+visual*15),pr=hook&&p.promise?(overlap(hook.content,p.promise)?82:30):30,score=Math.round(hs*.31+cl*.22+pa*.22+pr*.17+(p.blocks.some(b=>b.type==='CTA')?8:0));const rawIcn=Math.round(Math.max(0,Math.min(100,score)));const recent=calRecords.slice(-5);const reference=recent.length>=5?recent.reduce((sum,x)=>sum+Number(x.apv||0),0)/recent.length:null;const icn=reference===null?rawIcn:Math.round(rawIcn*.7+reference*.3);return{hs:Math.round(hs),cl:Math.round(cl),pa:Math.round(pa),pr,score:icn,rawIcn,calibrated:reference!==null,reference:reference&&Math.round(reference),r}}
function analysis(){if(!analysisDirty&&cachedAnalysis)return cachedAnalysis;cachedAnalysis=computeAnalysis();analysisDirty=false;return cachedAnalysis}
function markAnalysisDirty(){analysisDirty=true;cachedAnalysis=null}
function overlap(a,b){let x=new Set((a||'').toLowerCase().match(/[\p{L}]{4,}/gu)||[]),y=new Set((b||'').toLowerCase().match(/[\p{L}]{4,}/gu)||[]);return[...x].some(w=>y.has(w))}
function quality(b,a){if(!b.content&&b.type!=='VISUAL')return['Vacío','bad'];let r=a.r.find(x=>x[2]===b.id);return r?[r[0]==='bad'?'Crítico':'Revisar',r[0]]:['Óptimo','good']}
function render(){ $('#title').value=p.title;$('#promise').value=p.promise;$('#wpm').value=p.wpm||150;$('#wpm-value').textContent=p.wpm||150;let a=analysis(),flow=$('#flow');$('#empty').hidden=!!p.blocks.length;if(flowDirty){flow.innerHTML=p.blocks.map((b,i)=>{let[n,c]=T[b.type],q=quality(b,a);return`<article draggable="true" class="flow-block ${sel===b.id?'selected':''}" data-id="${b.id}" style="--color:${c}"><header>${n}<span>· ${i+1}</span></header><h3>${esc(b.label||n)}</h3><textarea class="inline-block-editor" data-inline="${b.id}" placeholder="Pegá o escribí el contenido del bloque…">${esc(b.content)}</textarea><footer>${W(b.content)} palabras · ${D(b.content)} s <b class="quality ${q[1]}">${q[0]}</b><button class="delete-inline" data-delete="${b.id}" title="Eliminar bloque" aria-label="Eliminar bloque">×</button></footer></article>`}).join('');bindBlocks();flowDirty=false;}renderEdit(a);renderMetrics(a);scheduleAI();renderTimeline();renderTele();draw(a); }
function bindBlocks(){$$('.flow-block').forEach(e=>{e.onclick=event=>{if(event.target.matches('textarea'))return;sel=e.dataset.id;render()};const text=e.querySelector('.inline-block-editor');if(text){const grow=()=>{text.style.height='auto';text.style.height=text.scrollHeight+'px'};grow();text.oninput=()=>{const b=p.blocks.find(x=>x.id===text.dataset.inline);if(!b)return;b.content=text.value;grow();save();renderMetrics(analysis());scheduleAI()};text.onclick=event=>event.stopPropagation()}const remove=e.querySelector('[data-delete]');if(remove)remove.onclick=event=>{event.stopPropagation();const id=remove.dataset.delete;p.blocks=p.blocks.filter(b=>b.id!==id);if(sel===id)sel=null;flowDirty=true;save();render()};e.ondragstart=x=>{if(x.target.matches('textarea'))return;x.dataTransfer.setData('id',e.dataset.id)};e.ondragover=x=>{x.preventDefault();e.classList.add('dragover')};e.ondragleave=()=>e.classList.remove('dragover');e.ondrop=x=>{x.preventDefault();let id=x.dataTransfer.getData('id'),from=p.blocks.findIndex(b=>b.id===id),to=p.blocks.findIndex(b=>b.id===e.dataset.id);if(from>=0&&to>=0&&from!==to){let[b]=p.blocks.splice(from,1);p.blocks.splice(to,0,b);flowDirty=true;save();render()}}})}
function renderEdit(a){let b=p.blocks.find(x=>x.id===sel),f=$('#editor');$('#no-selection').hidden=!!b;f.hidden=!b;if(!b)return;$('#type').value=b.type;$('#label').value=b.label;$('#content').value=b.content;$('#notes').value=b.notes;$('#info').textContent=`${W(b.content)} palabras · ${D(b.content)} s · ${quality(b,a)[0]}`}
function renderMetrics(a){$('#score').textContent=a.score;$('#bar').style.width=a.score+'%';$('#metric-grid').innerHTML=[['Hook',a.hs],['Claridad FH',a.cl],['Ritmo',a.pa],['Promesa',a.pr],...(aiResult?[['IA: Hook–promesa',Math.round(aiResult.alignment*100)],['IA: Redundancia',Math.round(aiResult.redundancy*100)]]:[])].map(x=>`<div>${x[0]}<b>${x[1]}</b></div>`).join('');const baseRisks=a.r.map(x=>`<li class="${x[0]}">${x[1]}</li>`).join('')||'<li class="good">Sin riesgos principales.</li>';const explain=aiResult?`<li class="ai-insight"><b>✦ Diagnóstico IA local activo</b>Procesó título, promesa, Hook y ${p.blocks.length} bloque(s) dentro de este navegador. Alineación Hook–promesa: ${Math.round(aiResult.alignment*100)}%. Redundancia máxima: ${Math.round(aiResult.redundancy*100)}%.</li>`:`<li class="ai-insight"><b>◌ Diagnóstico IA no activo</b>Se usan reglas de estructura, duración, claridad y ritmo. Activá Embeddings para analizar relación semántica local.</li>`;$('#risks').innerHTML=baseRisks+explain;renderHeuristics()}
function renderTimeline(){let s=0;$('#timeline-list').innerHTML=p.blocks.map((b,i)=>{let t=s;s+=D(b.content);return`<div class="timeline-item"><small>${time(t)}</small><i class="dot" style="background:${T[b.type][1]}"></i><button data-go="${b.id}">${i+1}. ${esc(b.label||T[b.type][0])}</button><small>${D(b.content)}s</small></div>`}).join('');$$('[data-go]').forEach(x=>x.onclick=()=>{sel=x.dataset.go;view('canvas');render()})}
function renderTele(){$('#teletext').innerHTML=p.blocks.filter(b=>b.content).map(b=>`<section class="tele-section"><small>${T[b.type][0]}</small><p>${esc(b.content)}</p></section>`).join('')||'<p>Sin contenido para leer.</p>'}
function draw(a){let c=$('#chart'),x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.strokeStyle='#303b53';for(let y=35;y<h;y+=40){x.beginPath();x.moveTo(30,y);x.lineTo(w-10,y);x.stroke()}x.strokeStyle='#32d2ac';x.lineWidth=3;x.beginPath();x.moveTo(30,18);x.bezierCurveTo(100,55,130,60+(100-a.hs)/2,180,70);x.bezierCurveTo(300,95,380,100+(100-a.pa)/3,w-12,h-a.score*1.5);x.stroke();x.fillStyle='#9aa8c0';x.font='11px sans-serif';x.fillText('ICN '+a.score+'/100',35,17)}
function renderCal(){all('calibrations').then(rows=>{$('#caldata').innerHTML=rows.length?rows.map(r=>`<p>${r.format} · ${r.genre}: <b>${r.apv}%</b></p>`).join(''):'<small>Sin datos todavía.</small>'})}
function save(){markAnalysisDirty();clearTimeout(timer);timer=setTimeout(async()=>{p.title=$('#title').value||'Nuevo guion';p.promise=$('#promise').value;p.updatedAt=Date.now();await put('projects',p);if(Date.now()-(p.lastSnapshotAt||0)>1800000){p.lastSnapshotAt=Date.now();await put('snapshots',{id:crypto.randomUUID(),projectId:p.id,createdAt:p.lastSnapshotAt,data:structuredClone(p)})}},350)}
function add(type='HOOK'){p.blocks.push({id:crypto.randomUUID(),type,label:T[type][0],content:'',notes:''});flowDirty=true;sel=p.blocks.at(-1).id;save();render()}
function move(n){let i=p.blocks.findIndex(b=>b.id===sel),j=i+n;if(j>=0&&j<p.blocks.length){[p.blocks[i],p.blocks[j]]=[p.blocks[j],p.blocks[i]];flowDirty=true;save();render()}}
function view(id){$$('.panel').forEach(x=>x.classList.toggle('on',x.id===id));$$('.view').forEach(x=>x.classList.toggle('on',x.dataset.view===id))}
// Los modelos se administran exclusivamente por Cache Storage del navegador.
// No se escribe ninguna carpeta física ni se usa File System Access.
async function downloadModel(){
  const status=$('#model-download-status'), progress=$('#model-download-progress');
  progress.hidden=false;progress.value=5;status.textContent='Preparando descarga local…';
  await initWorker(true);
  progress.value=100;status.textContent='✓ Modelo listo en este navegador.';
}
function contentHash(value){let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
function scheduleAI(){
  clearTimeout(aiTimer);
  if(p.aiMode!=='embeddings'||!worker)return;
  aiTimer=setTimeout(async()=>{
    const texts=[{id:'title',text:p.title,role:'title'},{id:'promise',text:p.promise,role:'promise'},...p.blocks.map(b=>({id:b.id,text:b.content,role:'block'}))];
    const hook=p.blocks.find(b=>b.type==='HOOK');if(hook)texts.push({id:'hook',text:hook.content,role:'hook'});
    const id='embedding-'+contentHash(JSON.stringify(texts));const cached=await get('analysisCache',id);
    if(cached?.result){aiResult=cached.result;setAIActivity('semantic','✦ IA: resultado local en caché');renderMetrics(analysis());return}
    worker.postMessage({type:'EMBED',requestId:++rev,cacheId:id,texts});
  },700);
}
function setAIActivity(kind,text){const el=$('#ai-activity');if(!el)return;el.className='ai-activity '+kind;el.textContent=text;el.title=text;}
async function initWorker(activate=false){
  worker?.terminate();
  $('#ai-state').textContent=p.aiMode==='basic'?'IA: heurísticas locales':'IA: modelo local configurado';
  setAIActivity(p.aiMode==='basic'?'heuristic':'loading',p.aiMode==='basic'?'◌ IA: heurística':'◌ IA: preparando modelo local');
  if(p.aiMode==='basic'||!activate)return;
  return new Promise((resolve,reject)=>{try{worker=new Worker('./ai-worker.js',{type:'module'});worker.onmessage=event=>{const d=event.data;if(d.type==='PROGRESS'){setAIActivity('loading','◌ IA: '+d.message);const pct=Number((d.message.match(/(\d+)%/)||[])[1]);if(Number.isFinite(pct)){$('#model-download-progress').hidden=false;$('#model-download-progress').value=pct}}if(d.type==='READY'){setAIActivity('semantic','✦ IA: modelo local listo');resolve()}if(d.type==='EMBED_RESULT'){aiResult=d;put('analysisCache',{id:d.cacheId||'embedding-'+Date.now(),projectId:p.id,updatedAt:Date.now(),result:d});setAIActivity('semantic','✦ IA: analizó '+p.blocks.length+' bloque(s) localmente');renderMetrics(analysis())}if(d.type==='ERROR'){setAIActivity('error','! IA: error local');reject(new Error(d.message))}};worker.postMessage({type:'INIT',mode:p.aiMode,revision:++rev})}catch(error){reject(error)}})
}
function bind(){ $$('#palette [data-type]').forEach(button=>button.addEventListener('dragstart',event=>{event.dataTransfer.setData('type',button.dataset.type);event.dataTransfer.effectAllowed='copy'}));$('#viewport').ondragover=e=>e.preventDefault();$('#viewport').ondrop=e=>{e.preventDefault();let t=e.dataTransfer.getData('type');if(t)add(t)};$('#title').oninput=save;$('#wpm').oninput=()=>{p.wpm=+$('#wpm').value;$('#wpm-value').textContent=p.wpm;save();render()};$('#promise').oninput=()=>{save();renderMetrics(analysis())};['type','label','content','notes'].forEach(k=>$('#'+k).oninput=()=>{let b=p.blocks.find(x=>x.id===sel);if(!b)return;b[k]=$('#'+k).value;save();render()});$('#del').onclick=()=>{p.blocks=p.blocks.filter(b=>b.id!==sel);sel=null;flowDirty=true;save();render()};$('#up').onclick=()=>move(-1);$('#down').onclick=()=>move(1);$$('.view').forEach(b=>b.onclick=()=>view(b.dataset.view));$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('on',x===b));$$('.tabpage').forEach(x=>x.classList.toggle('on',x.id===b.dataset.tab));if(b.dataset.tab==='cal')renderCal()});$('#new').onclick=()=>{if(!confirm('¿Crear un proyecto nuevo? Exportá el actual si querés conservarlo.'))return;p={id:'active',title:'Nuevo guion',promise:'',format:'long',genre:'educativo',aiMode:'basic',wpm:150,blocks:[],updatedAt:Date.now()};sel=null;aiResult=null;flowDirty=true;markAnalysisDirty();save();render()};$('#export').onclick=()=>{const menu=$('#export-menu');menu.hidden=!menu.hidden;$('#export').setAttribute('aria-expanded',String(!menu.hidden))};$$('[data-export]').forEach(button=>button.onclick=async()=>{const a=analysis(),c=await all('calibrations'),kind=button.dataset.export;if(kind==='md')exportMarkdown(p,a);else if(kind==='html')exportHTML(p,a);else exportJSON(p,a,c);$('#export-menu').hidden=true});$('#theme').onclick=()=>document.body.classList.toggle('light');
  const syncPanels=()=>{const l=document.body.classList.contains('left-collapsed'),r=document.body.classList.contains('right-collapsed');$('#toggle-left').classList.toggle('active',l);$('#toggle-right').classList.toggle('active',r);$('#toggle-left').setAttribute('aria-pressed',String(l));$('#toggle-right').setAttribute('aria-pressed',String(r));};
  $('#toggle-left').onclick=()=>{document.body.classList.toggle('left-collapsed');syncPanels()};
  $('#toggle-right').onclick=()=>{document.body.classList.toggle('right-collapsed');syncPanels()};
  syncPanels();
  const downloadButton=$('#download-model');
  const paintMode=()=>{const ai=p.aiMode==='embeddings';$('#mode-basic').classList.toggle('active',!ai);$('#mode-ai').classList.toggle('active',ai);$('#ai-download-area').hidden=!ai;$('#basic-state').hidden=ai;};
  $('#mode-basic').onclick=()=>{p.aiMode='basic';aiResult=null;initWorker(false);save();paintMode()};
  $('#mode-ai').onclick=()=>{p.aiMode='embeddings';paintMode()};
  if(downloadButton)downloadButton.onclick=async event=>{event.preventDefault();downloadButton.disabled=true;try{await downloadModel();save()}catch(error){$('#model-download-status').textContent='No se pudo descargar el modelo.';console.error(error)}finally{downloadButton.disabled=false}};
  $('#ai').onclick=()=>{const dialog=$('#aidialog');paintMode();if(typeof dialog.showModal==='function')dialog.showModal();else{dialog.setAttribute('open','');dialog.style.display='block';}};
  $('#close-ai').onclick=()=>$('#aidialog').close?.();$('#calform').onsubmit=async e=>{e.preventDefault();await put('calibrations',{id:crypto.randomUUID(),format:$('#format').value,genre:$('#genre').value,apv:+$('#apv').value,r30:+$('#r30').value||null,createdAt:Date.now()});e.target.reset();calRecords=await all('calibrations');renderCal();renderMetrics(analysis())};const speakAt=i=>{const list=p.blocks.filter(b=>b.content);if(!list.length)return;tts.index=Math.max(0,Math.min(i,list.length-1));speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(list[tts.index].content);u.lang='es-AR';u.rate=+$('#rate').value;tts.playing=true;u.onend=()=>{if(tts.playing&&tts.index<list.length-1)speakAt(tts.index+1)};speechSynthesis.speak(u)};$('#speak').onclick=()=>{if(tts.paused){speechSynthesis.resume();tts.paused=false}else speakAt(tts.index)};$('#pause-speak').onclick=()=>{if(tts.playing){speechSynthesis.pause();tts.paused=true}};$('#prev-speak').onclick=()=>speakAt(tts.index-1);$('#next-speak').onclick=()=>speakAt(tts.index+1);$('#full').onclick=()=>$('#tele').requestFullscreen();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=11')}
boot().catch(error=>{console.error(error);const message='ScriptLab no pudo iniciarse: '+error.message;document.body.insertAdjacentHTML('afterbegin','<div style="padding:12px;background:#ff6879;color:#20101a;position:fixed;z-index:9999;left:0;right:0;top:0">'+message+'</div>');});
